import { ProfileData } from "./types"

// Mock data - en réalité, cela viendrait d'une API
export const mockProfile: ProfileData = {
  id: "1",
  name: "Marie Dubois",
  type: "human",
  avatar: "/placeholder.svg?height=120&width=120",
  coverImage: "/placeholder.svg?height=200&width=800",
  title: "Développeuse Full-Stack Senior",
  description:
    "Passionnée par le développement web moderne, je crée des applications performantes et intuitives. Avec plus de 8 ans d'expérience, je maîtrise l'écosystème React/Next.js et les architectures cloud. J'accompagne mes clients de la conception à la mise en production.",
  location: "Paris, France",
  languages: ["Français", "Anglais", "Espagnol"],
  responseTime: "< 2h",
  joinedDate: "2020-03-15",
  isOnline: true,
  rating: 4.9,
  totalReviews: 127,
  completedProjects: 89,
  skills: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "AWS", "Docker", "Tailwind CSS"],
  hourlyRate: "45€",
  projectRate: "2500-8000€",
  availability: "Disponible immédiatement",
  portfolio: [
    "https://github.com/marie-dubois",
    "https://portfolio.marie-dubois.dev",
    "https://linkedin.com/in/marie-dubois",
  ],
  certifications: ["AWS Solutions Architect", "Google Cloud Professional"],
  missions: [
    {
      id: "1",
      title: "Plateforme e-commerce B2B",
      client: "TechCorp",
      duration: "3 mois",
      completedAt: "2024-01-15",
      rating: 5,
      budget: "12000€",
      description:
        "Développement complet d'une plateforme e-commerce avec gestion des stocks et facturation automatisée.",
      technologies: ["Next.js", "PostgreSQL", "Stripe", "AWS"],
    },
    {
      id: "2",
      title: "Application mobile React Native",
      client: "StartupXYZ",
      duration: "2 mois",
      completedAt: "2023-11-20",
      rating: 5,
      budget: "8000€",
      description: "Application mobile de gestion de tâches avec synchronisation temps réel.",
      technologies: ["React Native", "Firebase", "Redux"],
    },
    {
      id: "3",
      title: "Refonte site vitrine",
      client: "AgenceDesign",
      duration: "1 mois",
      completedAt: "2023-09-10",
      rating: 4,
      budget: "3500€",
      description: "Modernisation complète du site avec optimisation SEO et performances.",
      technologies: ["Next.js", "Tailwind CSS", "Vercel"],
    },
  ],
  reviews: [
    {
      id: "1",
      client: "Thomas Martin",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 5,
      date: "2024-01-20",
      comment:
        "Travail exceptionnel ! Marie a livré exactement ce que nous attendions, dans les délais et avec une qualité irréprochable. Communication parfaite tout au long du projet.",
      project: "Plateforme e-commerce B2B",
      helpful: 12,
    },
    {
      id: "2",
      client: "Sophie Laurent",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 5,
      date: "2023-12-05",
      comment:
        "Très professionnelle et réactive. L'application développée dépasse nos attentes. Je recommande vivement !",
      project: "Application mobile React Native",
      helpful: 8,
    },
    {
      id: "3",
      client: "Pierre Durand",
      avatar: "/placeholder.svg?height=40&width=40",
      rating: 4,
      date: "2023-09-15",
      comment:
        "Bon travail dans l'ensemble. Quelques ajustements ont été nécessaires mais le résultat final est satisfaisant.",
      project: "Refonte site vitrine",
      helpful: 5,
    },
  ],
  ratingBreakdown: {
    5: 89,
    4: 28,
    3: 7,
    2: 2,
    1: 1,
  },
}
